name: RPGChat
version: 1.0
author: cuzitsjonny
softdepend: [Rolecraft, Vault]

main: com.github.cuzitsjonny.rpgchat.RPGChatPlugin

commands:
    reloadrpgchat:
        description: Reloads config entries of RPGChat.
        permission: rpgchat.reload
    ooc:
        description: Sends a global chat message.
        permission: rpgchat.ooc
    whisper:
        description: Sends a local chat message with decreased range.
        permission: rpgchat.whisper
    yell:
        description: Sends a local chat message with increased range.
        permission: rpgchat.yell

permissions:
    rpgchat.reload:
        default: op
    rpgchat.ooc:
        default: true
    rpgchat.color:
        default: op
    rpgchat.whisper:
        default: true
    rpgchat.yell:
        default: true